version: "3"
services:
  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    networks:
      - grafananet
    hostname: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    restart: always
    tty: true
    user: "472"
    volumes:
      - ./grafana:/var/lib/grafana:rw
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
    working_dir: /usr/share/grafana
  influxdb:
    command:
      - influxd
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=nodered
      - DOCKER_INFLUXDB_INIT_ORG=MAPPERORG
      - DOCKER_INFLUXDB_INIT_USERNAME=MYUSERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=MYPASSWORD
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=g8Sus5C4h3SisnymoBVrMh56NVf_kfvkIG5MQBC0pVKhimNBv_Gf4pDk7ujdoGKYZRREQzy3C9q7EaaN_YGykA==
      - GOSU_VER=1.12
      - INFLUX_CONFIGS_PATH=/etc/influxdb2/influx-configs
    networks:
      - grafananet
    hostname: influxdb2
    image: influxdb:latest
    ports:
      - 3001:8086/tcp
    restart: always
    tty: true
    volumes:
      - ./influx/data:/var/lib/influxdb2:rw
      - ./influx/config:/etc/influxdb2:rw
  nodered:
    container_name: nodered
    environment:
      - NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules
      - FLOWS=flows.json
    networks:
      - grafananet
    hostname: nodered
    image: nodered/node-red:latest
    ports:
      - 3002:1880/tcp
    restart: always
    tty: true
    user: node-red
    volumes:
      - ./nodered/data:/data:rw
    working_dir: /usr/src/node-red
networks:
    grafananet:
        driver: bridge