version: "3"
services:
  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    networks:
      - grafananet
    hostname: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000/tcp
    restart: always
    tty: true
    user: "472"
    volumes:
      - ~/docker/grafana:/var/lib/grafana:rw
    working_dir: /usr/share/grafana
  influxdb:
    command:
      - influxd
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=nodered
      - DOCKER_INFLUXDB_INIT_ORG=   MYORG
      - DOCKER_INFLUXDB_INIT_PASSWORD= MYPASSWORD
      - DOCKER_INFLUXDB_INIT_USERNAME= MYUSERNAME
      - GOSU_VER=1.12
      - INFLUXDB_VERSION=2.1.1
      - INFLUX_CLI_VERSION=2.2.1
      - INFLUX_CONFIGS_PATH=/etc/influxdb2/influx-configs
      - INFLUXD_INIT_PORT=9999
      - INFLUXD_INIT_PING_ATTEMPTS=600
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=default
    networks:
      - grafananet
    hostname: influxdb2
    image: influxdb:latest
    ports:
      - 3001:3001/tcp
    networks:
      - grafananet
    restart: always
    tty: true
    volumes:
      - ~/docker/influxdb/data:/var/lib/influxdb2:rw
      - ~/docker/influxdb/config:/etc/influxdb2:rw
  nodered:
    container_name: nodered
    environment:
      - NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules
      - FLOWS=flows.json
    networks:
      - grafananet
    hostname: nodered
    image: nodered/node-red:latest
    ports:
      - 3002:3002/tcp
    restart: always
    tty: true
    user: node-red
    volumes:
      - ~/docker/nodered/data:/data:rw
    working_dir: /usr/src/node-red
  networks:
    grafananet:
      external: true

