version: "3"
services:
  influxdb:
    command:
      - influxd
    container_name: influxdb
    entrypoint:
      - /entrypoint.sh
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_BUCKET=nodered
      - DOCKER_INFLUXDB_INIT_ORG=   /////YOUR ORG GOES HERE////
      - DOCKER_INFLUXDB_INIT_PASSWORD= ///YOUR INFLUX LOGIN PASSWORD GOES HERE////
      - DOCKER_INFLUXDB_INIT_USERNAME= ///YOUR INFLUX LOGIN USERNAME ////
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GOSU_VER=1.12
      - INFLUXDB_VERSION=2.1.1
      - INFLUX_CLI_VERSION=2.2.1
      - INFLUX_CONFIGS_PATH=/etc/influxdb2/influx-configs
      - INFLUXD_INIT_PORT=9999
      - INFLUXD_INIT_PING_ATTEMPTS=600
      - DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=default
    hostname: influxdb2
    image: influxdb:latest
    ipc: private
    logging:
      driver: db
      options: {}
    ports:
      - 0.0.0.0:8086:8086/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /volume2/docker/influxdb/data:/var/lib/influxdb2:rw
      - /volume2/docker/influxdb/config:/etc/influxdb2:rw
