{
 "title": "Helium Mapper Influx2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mapper_data",
     "query": "\n  from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mapper\" and r._field == \"battery\")\n  |> drop(columns: [\"geohash\"])\n  |> aggregateWindow(every:v.windowPeriod , fn: last, createEmpty: false)\n  ",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mapper\" and r._field == \"speed\")\n  |> drop(columns: [\"geohash\"])\n  |> aggregateWindow(every:v.windowPeriod , fn: mean, createEmpty: false)\n  ",
     "select": [
      [
       { "params": [ "speed" ], "type": "field" },
       { "params": [ "speed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "unique hs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mapper\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hotspot_name\")\n  |> drop(columns: [\"name\", \"_field\",\"_measurement\", \"geohash\"])\n  |> unique(column: \"_value\")\n  |> count(column: \"_value\")",
     "select": [
      [
       { "params": [ "hotspot_name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Hotspot",
   "type": "stat",
   "description": "Chooses any random hotspot out of the last uplink packet. ",
   "gridPos": { "h": 2, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mapper\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hotspot_name\" or r[\"_field\"] == \"reported_at\")\n  |> group(columns: [\"_measurement\", \"_field\"], mode: \"by\")\n  |> drop(columns: [\"_measurement\",\"geohash\"])\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false, column: \"reported_at\")\n  |> sort(columns: [\"reported_at\"], desc: true)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"])\n  |> yield(name: \"last_hotspot\")",
     "select": [
      [
       { "params": [ "hotspot_name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Reported at",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mapper\" and r._field == \"reported_at\")\n  |> drop(columns: [\"geohash\", \"name\", \"_measurement\"])\n  |> sort(columns: [\"_value\"], desc: true)\n  |> distinct(column: \"_value\")\n  |> drop(columns:[\"_start\",\"_stop\",\"_field\"])\n  |> yield(name: \"last_seen\")\n  ",
     "select": [
      [
       { "params": [ "reported_at" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DataCredits left",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mapper\" and r._field == \"dc_balance\")\n  |> drop(columns: [\"geohash\", \"name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"credits\")\n ",
     "select": [
      [
       { "params": [ "hotspot_name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Tracker",
   "type": "grafana-worldmap-panel",
   "description": "Shows current path of Mapper location with strongest hotspot signal ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "geohash" ], "type": "tag" }
     ],
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mapper\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hotspot_name\" or r[\"_field\"] == \"hslat\" or r[\"_field\"] == \"hslong\" or r[\"_field\"] == \"rssi\" or r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\")\n  |> group(columns:[\"_measurement\", \"_field\"], mode:\"by\")\n  |> drop(columns: [\"_measurement\",\"_start\",\"_stop\"])\n  |> pivot(rowKey: [\"_time\",\"geohash\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> highestMax(\n    n:1000,\n    column: \"rssi\",\n    groupColumns: [\"geohash\"],\n)\n|> sort(columns:[\"_time\"], desc: false)\n\n  |> yield(name: \"location_bestsignal\")",
     "select": [
      [
       { "params": [ "hotspot_name" ], "type": "field" }
      ],
      [
       { "params": [ "rssi" ], "type": "field" }
      ],
      [
       { "params": [ "snr" ], "type": "field" }
      ],
      [
       { "params": [ "spreading" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Raw data",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mapper\")\n  |> group(columns:[\"_measurement\", \"_field\"], mode:\"by\")\n  |> drop(columns: [\"_measurement\",\"_start\",\"_stop\"])\n  |> pivot(rowKey: [\"_time\",\"geohash\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> sort(columns: [\"reported_at\"], desc: true)\n  |> yield(name: \"_rawdata\")"
    }
   ]
  },
  {
   "title": "Hotspot Coverage",
   "type": "geomap",
   "description": "Marks Mapper Position with X and Hotspot Location with a circle. Its color represents the RSSI strength.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "geohash" ], "type": "tag" }
     ],
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mapper\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hotspot_name\" or r[\"_field\"] == \"hslat\" or r[\"_field\"] == \"hslong\" or r[\"_field\"] == \"rssi\" or r[\"_field\"] == \"snr\" or r[\"_field\"] == \"spreading\" or r[\"_field\"] == \"sats\" or r[\"_field\"] == \"lat\" or r[\"_field\"] == \"lon\" or r[\"_field\"] == \"distance_km\" )\n  |> group(columns:[\"_measurement\", \"_field\"], mode:\"by\")\n  |> drop(columns: [\"_measurement\",\"_start\",\"_stop\"])\n  |> pivot(rowKey: [\"_time\",\"geohash\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n    |> map(fn:(r) => ({ r with hslat: float(v: r.hslat) }))\n    |> map(fn:(r) => ({ r with hslong: float(v: r.hslong) }))\n    |> sort(columns: [\"_time\"], desc: true)\n    |> yield(name: \"geohash\")",
     "select": [
      [
       { "params": [ "hotspot_name" ], "type": "field" }
      ],
      [
       { "params": [ "rssi" ], "type": "field" }
      ],
      [
       { "params": [ "snr" ], "type": "field" }
      ],
      [
       { "params": [ "spreading" ], "type": "field" }
      ],
      [
       { "params": [ "hslat" ], "type": "field" }
      ],
      [
       { "params": [ "hslong" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "" }
     ]
    }
   ]
  },
  {
   "title": "Hotspots per Uplink",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mapper_data",
     "query": "from(bucket: \"nodered\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mapper\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hotspot_name\")\n  |> drop(columns: [\"name\", \"_field\",\"_measurement\"])\n  |> count()\n  |> yield(name: \"count\")",
     "select": [
      [
       { "params": [ "hotspot_name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}